### PR TITLE
Apply BCROSS_DIODE_SKY aka HV phase corrections

### PR DESCRIPTION
**Pull request by ludwigschwardt**
This is also known as "Phase Two of Polarisation Calibration". It does both Phase 2A (`BCROSS_DIODE`: HV phase derived from noise diode) and 2B (`BCROSS_DIODE_SKY`: noise diode HV phase transformed to sky).

Fire the noise diodes as part of phase-up (both initially and during verification). This triggers the cal pipeline to produce `KCROSS_DIODE` and `BCROSS_DIODE_SKY` solutions. Get those solutions from telstate and combine them with the K and B solutions, respectively.

Also do a few tweaks to the script logger output to synchronise this script with `calibrate_delays`, and remove somewhat spurious logs.

This addresses JIRA tickets [SR-1940](https://skaafrica.atlassian.net/browse/SR-1940) and [SR-1980](https://skaafrica.atlassian.net/browse/SR-1980).

### CODE REVIEW

**Comment by ludwigschwardt** [comment]
Yes!

The one thing to look out for: the noise diode will now also fire during phase-up, resulting in larger noise and higher signal levels when solving for gains. I'm interested whether this has any negative impact on the beamformer.

**Comment by ludwigschwardt** [comment]
I have now rolled `BCROSS_DIODE_SKY` support into this PR, since it is only a few extra lines of code (most of the action has shifted to the cal pipeline). This will simplify deployment, since we have to roll out a triple whammy of new pipeline (SDP, ska-sa/katsdpcal#2) + new capture session (CAM, ska-sa/katcorelib#339) + new script (OBS, this PR)...

Please have a look at the last two commits:
 - The merge with master added narrowband support (capture-start all streams and not just correlator).
 - The final commit adds the BCROSS_DIODE_SKY bit.

**Comment by ludwigschwardt** [comment]
Sure, what's the use case? And does that imply not firing the noise diode?

**Comment by mserylak** [comment]
@ludwigschwardt, no we keep the noise diode firing et al. we just do not apply the corrections. With this option it is going to be easier for me to do verification tests.

**Comment by ludwigschwardt** [comment]
So let me summarise the suggested changes:

 - Add a `--disable-hv-correction` script option that still fires the noise diode to get *CROSS_DIODE* solutions in telstate, but don't apply them to F-engine gains
 - If no `BCROSS_DIODE_SKY` is found (like on current UHF / S-band), fall back to `BCROSS_DIODE` instead of doing no HV correction.

Does that sound OK?

**Comment by mserylak** [comment]
Yes, exactly that.

**Comment by ludwigschwardt** [comment]
@mserylak, have a look at the latest commit to check that it does what you want.

**Pull request merged**
