### PR TITLE
Limit length of dataset name in title

### PR DESCRIPTION
**Pull request by adriaanph**
Figure titles for RDB files are too long.

### CODE REVIEW

**Comment by ludwigschwardt** [comment]
Do you have an example CSV file where this helps? I struggle to see how the name is shortened, unless you have multiple datasets.

**Comment by ludwigschwardt** [comment]
@adriaanph - can you add an example here to help me understand?

**Comment by ludwigschwardt** [comment]
Hi @adriaanph, I added a different solution in #441. It restricts the number of datasets in the name to four:
```Python
datasets = np.unique(data['dataset']).tolist()
if len(datasets) > 4:
    datasets[2] = '...%d more...' % (len(datasets) - 3,)
    datasets[3] = datasets[-1]
datasets = datasets[:4]
```
If this solves your problem we can close this PR.

**Comment by ludwigschwardt** [comment]
You might also be interested in ska-sa/katdal#337 :-D

**Comment by ludwigschwardt** [comment]
@adriaanph, may I close this?

**Review by ludwigschwardt — COMMENTED** [review]
I think that the name scheme introduced by #441 makes this obsolete.

**Comment by adriaanph** [comment]
yes, #441 resolves this.

**Pull request closed without merging**
