### PR TITLE
Updating the L-band pickle files

### PR DESCRIPTION
**Pull request by Lavashni**
Updating the L-band rfi mask on github, update is for an rfi mask created on 2024-05-24. 

mask[:1]=True # bottom
mask[81:85]=True #intermittent
mask[92:126]=True #constant
mask[129:133]=True #more/less constant
mask[293:298]=True #more/less constant
mask[339:536]=True #constant
mask[673:677]=True # HI line
mask[740:746]=True #more/less constant
mask[791:902]=True #constant
mask[910:924]=True #intermittent RFI between these channels
mask[971:]=True # upper

Current rfi mask (red) compared to the old one (blue):

image

### CODE REVIEW

**Review by spassmoor — APPROVED** [review]
This looks ok

**Comment by spassmoor** [comment]
I just want to make sure we are not unflagging the 1380MHz  line . It is often a strong intermittent source

**Comment by Lavashni** [comment]
@spassmoor , would that be between channels 540 and 674?

**Comment by spassmoor** [comment]
mask[740:746]=True #more/less constant 
  1474.6  MHz to  , 1479.6 MHz   is New . do you know what it is ? 

The channels for RFI at 1378-> 1382 would be channels 624 to  630 .

**Comment by Lavashni** [comment]
@spassmoor , would the intermittent rfi in the 1380MHz region be seen only during the day or is it seen at night as well because this mask was created from an observation that ran at night.
I am not sure about what  caused the rfi in the 1474.6 MHz to 1479.6 MHz region, will have to check and get back to you on that one.
I attached the percentage of time data was flagged during this observation.
image

**Pull request merged**
